import type { Lesson } from "@/lib/types";

/**
 * Pillar A: Foundations. Ordered lesson curriculum per subsection (discipline).
 * Lesson order is the array order; prerequisites are bare ids within the same
 * subsection or "subId/lessonId" across subsections.
 */
export const A_CURRICULUM: Record<string, Lesson[]> = {
  A1: [
    {
      id: "vector-spaces",
      title: "Vector spaces & subspaces",
      goal: "Define a vector space and a subspace from the axioms, and see why closure under linear combination is the only property we ever use.",
    },
    {
      id: "basis-dimension",
      title: "Span, independence, basis, dimension",
      goal: "Build span and linear independence into the notion of a basis, prove that dimension is well defined, and read off coordinates.",
      prerequisites: ["vector-spaces"],
    },
    {
      id: "linear-maps-matrices",
      title: "Linear maps and matrices",
      goal: "Show every linear map between finite-dimensional spaces is a matrix once bases are fixed, and that composition is matrix multiplication.",
      prerequisites: ["basis-dimension"],
    },
    {
      id: "rank-nullity",
      title: "Rank, nullity, and the four fundamental subspaces",
      goal: "Prove the rank–nullity theorem and use the column/null/row/left-null spaces to decide when Ax=b is solvable.",
      prerequisites: ["linear-maps-matrices"],
    },
    {
      id: "norms",
      title: "Norms and the geometry of distance",
      goal: "Define norms via their three axioms, meet the p-norms, and connect L1/L2 to sparsity and Euclidean length.",
      prerequisites: ["vector-spaces"],
    },
    {
      id: "inner-products",
      title: "Inner products, orthogonality, Cauchy–Schwarz",
      goal: "Define the inner product, prove the Cauchy–Schwarz inequality, and derive angle and orthogonality from it.",
      prerequisites: ["norms"],
    },
    {
      id: "gram-schmidt",
      title: "Orthonormal bases & Gram–Schmidt",
      goal: "Construct an orthonormal basis by Gram–Schmidt, prove orthogonal matrices are isometries, and connect to the QR factorization.",
      prerequisites: ["inner-products", "basis-dimension"],
    },
    {
      id: "determinants",
      title: "Determinants and volume",
      goal: "Define the determinant as a signed volume scaling, derive its key properties, and tie det=0 to singularity.",
      prerequisites: ["linear-maps-matrices"],
    },
    {
      id: "eigenvalues",
      title: "Eigenvalues & eigenvectors",
      goal: "Define eigenpairs, find them through the characteristic polynomial, and interpret them as invariant scaling directions.",
      prerequisites: ["determinants"],
    },
    {
      id: "spectral-theorem",
      title: "Diagonalization & the spectral theorem",
      goal: "Prove that real symmetric matrices have real eigenvalues and an orthonormal eigenbasis, giving A = QΛQᵀ.",
      prerequisites: ["eigenvalues", "gram-schmidt"],
    },
    {
      id: "quadratic-forms",
      title: "Quadratic forms & positive definiteness",
      goal: "Read a quadratic form through the spectrum of its matrix, and use eigenvalue signs to test positive (semi)definiteness.",
      prerequisites: ["spectral-theorem"],
    },
    {
      id: "svd",
      title: "Singular value decomposition",
      goal: "Construct the SVD of any matrix from the spectral theorem applied to AᵀA, and read it as rotate–scale–rotate.",
      prerequisites: ["spectral-theorem"],
    },
    {
      id: "low-rank-pca",
      title: "Low-rank approximation (Eckart–Young) & PCA",
      goal: "Prove the truncated SVD is the best low-rank approximation, and identify PCA as the SVD of the centered data matrix.",
      prerequisites: ["svd"],
    },
    {
      id: "factorizations",
      title: "LU, QR, and Cholesky factorizations",
      goal: "See how LU, QR, and Cholesky each solve linear systems by structure, and why we factor instead of inverting.",
      prerequisites: ["gram-schmidt", "quadratic-forms"],
    },
    {
      id: "least-squares",
      title: "Least squares & the Moore–Penrose pseudo-inverse",
      goal: "Derive the normal equations from the residual, interpret the solution as a projection, and build the pseudo-inverse from the SVD.",
      prerequisites: ["svd", "factorizations"],
    },
    {
      id: "matrix-calculus",
      title: "Matrix calculus & the chain rule",
      goal: "Fix a layout convention, derive the gradients of the linear, quadratic, and affine forms, and compose them into backprop.",
      prerequisites: ["linear-maps-matrices"],
    },
    {
      id: "tensors-einsum",
      title: "Tensors & einsum",
      goal: "Generalize to higher-order tensors with index notation and the Einstein summation convention behind einsum.",
      prerequisites: ["matrix-calculus"],
    },
  ],
  A2: [
    {
      id: "probability-spaces",
      title: "Sample spaces, events, and the Kolmogorov axioms",
      goal: "Set up a probability space from the three axioms and compute probabilities of compound events.",
    },
    {
      id: "random-variables",
      title: "Random variables and distributions",
      goal: "Define random variables, their CDF, and the PMF/PDF, and tell discrete from continuous.",
      prerequisites: ["probability-spaces"],
    },
    {
      id: "expectation",
      title: "Expectation and the law of the unconscious statistician",
      goal: "Define expectation, prove linearity, and compute E[g(X)] without first finding the distribution of g(X).",
      prerequisites: ["random-variables"],
    },
    {
      id: "variance-moments",
      title: "Variance, moments, and moment generating functions",
      goal: "Define variance and higher moments, and use the MGF to recover them.",
      prerequisites: ["expectation"],
    },
    {
      id: "joint-distributions",
      title: "Joint, marginal, and conditional distributions",
      goal: "Work with joint distributions, marginalize, condition, and define independence.",
      prerequisites: ["random-variables"],
    },
    {
      id: "bayes-rule",
      title: "Conditional probability and Bayes' rule",
      goal: "Derive Bayes' rule and use it to invert conditional probabilities.",
      prerequisites: ["joint-distributions"],
    },
    {
      id: "common-distributions",
      title: "Bernoulli, Binomial, Poisson, Gaussian",
      goal: "Know the defining stories, PMFs/PDFs, and moments of the workhorse distributions.",
      prerequisites: ["variance-moments"],
    },
    {
      id: "exponential-family",
      title: "The exponential family and sufficient statistics",
      goal: "Write distributions in exponential-family form and read off sufficient statistics and natural parameters.",
      prerequisites: ["common-distributions"],
    },
    {
      id: "change-of-variables",
      title: "Transformations of random variables",
      goal: "Push a distribution through a function with the change-of-variables formula.",
      prerequisites: ["common-distributions"],
    },
    {
      id: "inequalities",
      title: "Markov, Chebyshev, and Jensen inequalities",
      goal: "Bound tail probabilities and relate E[f(X)] to f(E[X]) with the basic inequalities.",
      prerequisites: ["variance-moments"],
    },
    {
      id: "lln-clt",
      title: "Law of large numbers and the central limit theorem",
      goal: "State and use the LLN and CLT to describe the behavior of sample averages.",
      prerequisites: ["inequalities"],
    },
    {
      id: "mle",
      title: "Maximum likelihood estimation",
      goal: "Set up a likelihood, maximize its log, and estimate parameters from data.",
      prerequisites: ["common-distributions"],
    },
    {
      id: "map-conjugate",
      title: "MAP estimation and conjugate priors",
      goal: "Add a prior, compute the posterior, and use conjugacy to keep it in closed form.",
      prerequisites: ["bayes-rule", "mle"],
    },
    {
      id: "entropy",
      title: "Shannon entropy",
      goal: "Define entropy as expected surprise and derive its basic properties.",
      prerequisites: ["common-distributions"],
    },
    {
      id: "kl-cross-entropy",
      title: "KL divergence and cross-entropy",
      goal: "Define KL divergence, prove it is nonnegative, and connect cross-entropy to maximum likelihood.",
      prerequisites: ["entropy", "mle"],
    },
    {
      id: "mutual-information",
      title: "Mutual information",
      goal: "Define mutual information and read it as the KL divergence between the joint and the product of marginals.",
      prerequisites: ["kl-cross-entropy"],
    },
    {
      id: "markov-chains",
      title: "Markov chains and stationary distributions",
      goal: "Define a Markov chain by its transition matrix and find its stationary distribution.",
      prerequisites: ["joint-distributions", "A1/eigenvalues"],
    },
    {
      id: "information-geometry",
      title: "Fisher information and information geometry",
      goal: "Define the Fisher information, see it as the curvature of the log-likelihood, and meet the natural gradient.",
      prerequisites: ["mle", "kl-cross-entropy"],
    },
  ],
  A3: [
    {
      id: "optimization-landscape",
      title: "Optimization problems, minima, and gradients",
      goal: "Formalize an optimization problem and characterize minima through the gradient and the Hessian.",
      prerequisites: ["A1/matrix-calculus"],
    },
    {
      id: "convex-sets",
      title: "Convex sets",
      goal: "Define convex sets, recognize them, and use the separating-hyperplane idea.",
    },
    {
      id: "convex-functions",
      title: "Convex functions and their tests",
      goal: "Define convex functions and test convexity with the first- and second-order conditions.",
      prerequisites: ["convex-sets", "A1/quadratic-forms"],
    },
    {
      id: "gradient-descent",
      title: "Gradient descent",
      goal: "Derive gradient descent from a local model and analyze its descent guarantee.",
      prerequisites: ["optimization-landscape"],
    },
    {
      id: "convergence-rates",
      title: "Smoothness, strong convexity, and convergence rates",
      goal: "Use L-smoothness and strong convexity to prove sublinear and linear convergence rates.",
      prerequisites: ["gradient-descent", "convex-functions"],
    },
    {
      id: "sgd",
      title: "Stochastic gradient descent",
      goal: "Replace the full gradient with a stochastic estimate and understand the noise versus step-size tradeoff.",
      prerequisites: ["gradient-descent"],
    },
    {
      id: "momentum",
      title: "Momentum and Nesterov acceleration",
      goal: "Add momentum to gradient descent and see why acceleration improves the convergence rate.",
      prerequisites: ["convergence-rates"],
    },
    {
      id: "adaptive-methods",
      title: "AdaGrad, RMSProp, and Adam",
      goal: "Build per-coordinate adaptive step sizes and assemble the Adam update.",
      prerequisites: ["sgd", "momentum"],
    },
    {
      id: "constrained-optimization",
      title: "Constrained optimization and Lagrange multipliers",
      goal: "Turn an equality-constrained problem into stationarity of a Lagrangian.",
      prerequisites: ["optimization-landscape"],
    },
    {
      id: "duality",
      title: "Lagrangian duality",
      goal: "Form the dual problem, prove weak duality, and state when strong duality holds.",
      prerequisites: ["constrained-optimization", "convex-functions"],
    },
    {
      id: "kkt",
      title: "The KKT conditions",
      goal: "State the KKT conditions and use them to solve inequality-constrained problems.",
      prerequisites: ["duality"],
    },
    {
      id: "newton-method",
      title: "Newton's method",
      goal: "Derive Newton's method from a second-order model and analyze its quadratic convergence.",
      prerequisites: ["gradient-descent", "A1/spectral-theorem"],
    },
    {
      id: "quasi-newton",
      title: "Quasi-Newton methods (BFGS, L-BFGS)",
      goal: "Approximate the Hessian from gradient differences with the BFGS update and its limited-memory form.",
      prerequisites: ["newton-method"],
    },
    {
      id: "proximal-methods",
      title: "Proximal gradient methods",
      goal: "Define the proximal operator and use proximal gradient descent for nonsmooth objectives like the L1 penalty.",
      prerequisites: ["gradient-descent", "convex-functions"],
    },
    {
      id: "bayesian-optimization",
      title: "Bayesian optimization",
      goal: "Optimize an expensive black-box function with a Gaussian-process surrogate and an acquisition function.",
      prerequisites: ["A2/map-conjugate"],
    },
  ],
  A4: [
    {
      id: "floating-point",
      title: "Floating-point numbers and machine epsilon",
      goal: "Understand IEEE-754 floating point, machine epsilon, and where rounding error comes from.",
    },
    {
      id: "conditioning-stability",
      title: "Conditioning and numerical stability",
      goal: "Distinguish the conditioning of a problem from the stability of an algorithm, and bound error with the condition number.",
      prerequisites: ["floating-point", "A1/svd"],
    },
    {
      id: "catastrophic-cancellation",
      title: "Catastrophic cancellation",
      goal: "See how subtracting near-equal numbers destroys precision, and reformulate to avoid it.",
      prerequisites: ["floating-point"],
    },
    {
      id: "log-sum-exp",
      title: "The log-sum-exp trick and stable softmax",
      goal: "Derive the log-sum-exp shift and use it to compute softmax and log-likelihoods without overflow.",
      prerequisites: ["catastrophic-cancellation"],
    },
    {
      id: "iterative-methods",
      title: "Fixed-point and iterative methods",
      goal: "Solve equations by iteration and analyze convergence with the contraction-mapping idea.",
      prerequisites: ["conditioning-stability"],
    },
    {
      id: "conjugate-gradient",
      title: "The conjugate gradient method",
      goal: "Solve symmetric positive-definite systems with conjugate gradient and understand its Krylov structure.",
      prerequisites: ["iterative-methods", "A1/quadratic-forms"],
    },
    {
      id: "gmres",
      title: "Krylov subspaces and GMRES",
      goal: "Extend Krylov-subspace solving to nonsymmetric systems with GMRES.",
      prerequisites: ["conjugate-gradient"],
    },
    {
      id: "mixed-precision",
      title: "Mixed-precision arithmetic",
      goal: "Compare fp32, fp16, and bf16, and use loss scaling to compute stably in low precision.",
      prerequisites: ["floating-point"],
    },
  ],
  A5: [
    {
      id: "complexity-analysis",
      title: "Asymptotic complexity and Big-O",
      goal: "Analyze time and space with Big-O and Big-Theta, including amortized analysis.",
    },
    {
      id: "arrays-hashing",
      title: "Dynamic arrays and hash maps",
      goal: "Understand amortized O(1) append and average O(1) hashing, along with their failure modes.",
      prerequisites: ["complexity-analysis"],
    },
    {
      id: "linked-stacks-queues",
      title: "Linked lists, stacks, and queues",
      goal: "Build the linear structures and know when a linked layout beats a contiguous array.",
      prerequisites: ["complexity-analysis"],
    },
    {
      id: "trees-bst",
      title: "Binary search trees and balancing",
      goal: "Use a BST for ordered operations and see why balancing keeps them logarithmic.",
      prerequisites: ["complexity-analysis"],
    },
    {
      id: "heaps",
      title: "Heaps and priority queues",
      goal: "Implement a binary heap and use it for priority queues and heapsort.",
      prerequisites: ["trees-bst"],
    },
    {
      id: "sorting",
      title: "Comparison sorting and the n log n bound",
      goal: "Derive merge sort and quicksort, and prove the comparison-sort lower bound.",
      prerequisites: ["complexity-analysis"],
    },
    {
      id: "divide-and-conquer",
      title: "Divide and conquer and the master theorem",
      goal: "Solve divide-and-conquer recurrences with the master theorem.",
      prerequisites: ["sorting"],
    },
    {
      id: "dynamic-programming",
      title: "Dynamic programming",
      goal: "Recognize optimal substructure and overlapping subproblems, and build DP solutions.",
      prerequisites: ["divide-and-conquer"],
    },
    {
      id: "greedy",
      title: "Greedy algorithms and the exchange argument",
      goal: "Use greedy choices where they are optimal, and prove it with an exchange argument.",
      prerequisites: ["dynamic-programming"],
    },
    {
      id: "graph-traversal",
      title: "Graph representations, BFS, and DFS",
      goal: "Represent graphs and traverse them with breadth-first and depth-first search.",
      prerequisites: ["arrays-hashing"],
    },
    {
      id: "shortest-paths",
      title: "Shortest paths and Dijkstra",
      goal: "Find shortest paths with Dijkstra's algorithm and understand where it breaks.",
      prerequisites: ["graph-traversal", "heaps"],
    },
    {
      id: "mst",
      title: "Minimum spanning trees",
      goal: "Build minimum spanning trees with Kruskal and Prim, and prove the cut property.",
      prerequisites: ["shortest-paths"],
    },
    {
      id: "probabilistic-structures",
      title: "Bloom filters and HyperLogLog",
      goal: "Trade exactness for space with Bloom filters and cardinality sketches.",
      prerequisites: ["arrays-hashing", "A2/common-distributions"],
    },
  ],
};
