import type { Lesson } from "@/lib/types";

/**
 * Pillar D: Deep Learning (Core & Tracks). Ordered lesson curriculum per
 * subsection. Lesson order is the array order; prerequisites are bare ids
 * within the same subsection or "subId/lessonId" across subsections.
 */
export const D_CURRICULUM: Record<string, Lesson[]> = {
  D1: [
    {
      id: "mlp-forward",
      title: "Multi-layer perceptron",
      goal: "Stack affine maps and nonlinearities into an MLP, and trace one forward pass through its parameters.",
      prerequisites: ["A1/matrix-calculus"],
    },
    {
      id: "backprop",
      title: "Backpropagation",
      goal: "Derive backprop as the reverse-mode chain rule on the computational graph of an MLP.",
      prerequisites: ["mlp-forward"],
    },
    {
      id: "autodiff",
      title: "Reverse-mode autodiff",
      goal: "Implement a tiny autodiff engine with `Value` nodes that record their parents and compute gradients on a backward pass.",
      prerequisites: ["backprop"],
    },
    {
      id: "universal-approximation",
      title: "Universal approximation",
      goal: "State and use Cybenko / Hornik's theorem: one hidden layer with enough units can approximate any continuous function on a compact set.",
      prerequisites: ["mlp-forward"],
    },
    {
      id: "activations",
      title: "ReLU, GELU, Swish",
      goal: "Compare common nonlinearities and explain when each one is preferred, including the dead-ReLU failure mode.",
      prerequisites: ["mlp-forward"],
    },
    {
      id: "initialization",
      title: "Xavier and He initialization",
      goal: "Derive the variance-preserving initialization rules for tanh and ReLU networks, and see why bad initialization stalls training.",
      prerequisites: ["activations"],
    },
    {
      id: "normalization",
      title: "BatchNorm, LayerNorm, RMSNorm",
      goal: "Place normalization layers inside a network, derive their gradients, and pick the right variant per architecture.",
      prerequisites: ["initialization"],
    },
    {
      id: "regularization",
      title: "Dropout and weight decay",
      goal: "Combine stochastic dropout with L2 weight decay to regularize a deep network, and read each as a prior in disguise.",
      prerequisites: ["A3/proximal-methods"],
    },
    {
      id: "dl-optimizers",
      title: "Optimizers for deep learning",
      goal: "Move from SGD with momentum to Adam, AdamW, and learning-rate schedulers in the deep-learning regime.",
      prerequisites: ["A3/adaptive-methods", "regularization"],
    },
  ],
  D2: [
    {
      id: "convolution",
      title: "Convolution and pooling",
      goal: "Build the 2D convolution operation from sliding inner products, then add stride, padding, and pooling.",
      prerequisites: ["D1/mlp-forward"],
    },
    {
      id: "cnn-architectures",
      title: "Classic CNN architectures",
      goal: "Trace LeNet, AlexNet, VGG, and ResNet's skip connections, and see why depth without residuals collapses gradient flow.",
      prerequisites: ["convolution", "D1/backprop"],
    },
    {
      id: "modern-cnns",
      title: "Modern CNN families",
      goal: "Survey DenseNet, EfficientNet, and ConvNeXt, and the design decisions (compound scaling, large kernels) that made each one win.",
      prerequisites: ["cnn-architectures"],
      codeExempt: true,
    },
    {
      id: "vit",
      title: "Vision Transformers",
      goal: "Tokenize an image into patches and apply a standard Transformer encoder; understand the ViT inductive-bias tradeoffs.",
      prerequisites: ["cnn-architectures", "D3/transformer-arch"],
    },
    {
      id: "object-detection",
      title: "Object detection",
      goal: "Move from R-CNN's two-stage proposal-and-classify to YOLO's single-shot grid and DETR's set-prediction Transformer.",
      prerequisites: ["cnn-architectures"],
      codeExempt: true,
    },
    {
      id: "segmentation",
      title: "Semantic and instance segmentation",
      goal: "Use U-Net for per-pixel labels and Mask R-CNN for per-instance masks, and understand encoder-decoder skip connections.",
      prerequisites: ["object-detection"],
      codeExempt: true,
    },
    {
      id: "sam",
      title: "Segment Anything",
      goal: "Build the SAM promptable segmentation pipeline (image encoder, prompt encoder, mask decoder) and its foundation-model training story.",
      prerequisites: ["segmentation", "vit"],
      codeExempt: true,
    },
    {
      id: "ssl-vision",
      title: "Self-supervised vision (DINO, MAE)",
      goal: "Pretrain vision backbones without labels via student-teacher distillation (DINO) and masked image modeling (MAE).",
      prerequisites: ["vit"],
      codeExempt: true,
    },
    {
      id: "neural-rendering",
      title: "NeRF and Gaussian Splatting",
      goal: "Represent a 3D scene as a learned radiance field or a set of anisotropic Gaussians, and render novel views.",
      prerequisites: ["D1/mlp-forward"],
      codeExempt: true,
    },
  ],
  D3: [
    {
      id: "word-embeddings",
      title: "Word embeddings",
      goal: "Train word2vec (skip-gram with negative sampling) and contrast it with GloVe's matrix-factorization view.",
      prerequisites: ["D1/mlp-forward"],
    },
    {
      id: "rnn",
      title: "Recurrent networks",
      goal: "Define a vanilla RNN, unroll it through time, and see why long-range dependencies vanish or explode in the gradients.",
      prerequisites: ["D1/backprop"],
    },
    {
      id: "lstm-gru",
      title: "LSTM and GRU",
      goal: "Use gated recurrent cells to control information flow, fixing the vanishing-gradient problem of plain RNNs.",
      prerequisites: ["rnn"],
    },
    {
      id: "seq2seq-attention",
      title: "Seq2seq with attention",
      goal: "Build an encoder-decoder for translation, then add Bahdanau / Luong attention to let the decoder look back at every encoder state.",
      prerequisites: ["lstm-gru"],
    },
    {
      id: "self-attention",
      title: "Self-attention",
      goal: "Define scaled dot-product self-attention and explain why the softmax of QK^T gives a content-based mixing matrix.",
      prerequisites: ["seq2seq-attention"],
    },
    {
      id: "transformer-arch",
      title: "The Transformer",
      goal: "Assemble multi-head self-attention, position-wise FFNs, residuals, and LayerNorm into the encoder-decoder Transformer.",
      prerequisites: ["self-attention", "D1/normalization"],
    },
    {
      id: "positional-encoding",
      title: "Positional encodings",
      goal: "Compare sinusoidal, learned, ALiBi, and RoPE positional encodings, and see why position must be injected into self-attention.",
      prerequisites: ["transformer-arch"],
    },
    {
      id: "state-space-models",
      title: "State space models and Mamba",
      goal: "Replace attention with structured state space models (S4, Mamba) for linear-time sequence mixing.",
      prerequisites: ["transformer-arch"],
      codeExempt: true,
    },
    {
      id: "linear-attention",
      title: "Linear and sub-quadratic attention",
      goal: "Approximate softmax attention in linear time via kernel feature maps (Linformer, Performer) and IO-aware kernels (FlashAttention).",
      prerequisites: ["transformer-arch"],
      codeExempt: true,
    },
    {
      id: "hybrid-architectures",
      title: "Hybrid architectures",
      goal: "Combine attention and recurrence (RWKV, Hyena, Jamba, Griffin) to keep Transformer quality at lower context cost.",
      prerequisites: ["state-space-models", "linear-attention"],
      codeExempt: true,
    },
  ],
  D4: [
    {
      id: "autoencoders",
      title: "Autoencoders",
      goal: "Train an encoder-decoder pair to reconstruct inputs through a bottleneck, including the denoising variant.",
      prerequisites: ["D1/mlp-forward"],
    },
    {
      id: "vae",
      title: "Variational autoencoders",
      goal: "Derive the VAE's evidence lower bound and train it with the reparameterization trick.",
      prerequisites: ["autoencoders", "A2/kl-cross-entropy"],
    },
    {
      id: "vae-variants",
      title: "VAE variants (β-VAE, VQ-VAE)",
      goal: "Trade reconstruction for disentanglement with β-VAE, and use a discrete codebook with VQ-VAE.",
      prerequisites: ["vae"],
      codeExempt: true,
    },
    {
      id: "gan",
      title: "Generative adversarial networks",
      goal: "Train a generator and discriminator with the minimax objective; recognize mode collapse and instability.",
      prerequisites: ["autoencoders"],
    },
    {
      id: "gan-variants",
      title: "GAN variants (StyleGAN, BigGAN)",
      goal: "Survey StyleGAN's style-based generator and BigGAN's large-batch stabilization tricks.",
      prerequisites: ["gan"],
      codeExempt: true,
    },
    {
      id: "normalizing-flows",
      title: "Normalizing flows",
      goal: "Use invertible neural networks with tractable Jacobian determinants to model exact likelihoods.",
      prerequisites: ["A2/change-of-variables"],
    },
    {
      id: "diffusion",
      title: "Diffusion models",
      goal: "Define the forward Gaussian noising process, derive the reverse-time denoising objective, and train DDPM.",
      prerequisites: ["vae"],
    },
    {
      id: "latent-diffusion",
      title: "Latent diffusion",
      goal: "Run diffusion in a VAE's latent space (Stable Diffusion) and condition on text via cross-attention.",
      prerequisites: ["diffusion", "vae-variants"],
      codeExempt: true,
    },
    {
      id: "flow-matching",
      title: "Flow matching and consistency models",
      goal: "Train continuous-time generators by matching vector fields (flow matching, rectified flow) and distill them into one-step samplers (consistency models).",
      prerequisites: ["diffusion", "normalizing-flows"],
      codeExempt: true,
    },
  ],
  D5: [
    {
      id: "contrastive-ssl",
      title: "Contrastive self-supervision",
      goal: "Pretrain representations by pulling augmented views of the same image together (SimCLR, MoCo) using the InfoNCE loss.",
      prerequisites: ["D1/mlp-forward"],
    },
    {
      id: "clip",
      title: "CLIP and vision-language contrastive learning",
      goal: "Align images and captions in a shared embedding with contrastive loss across modalities.",
      prerequisites: ["contrastive-ssl"],
      codeExempt: true,
    },
    {
      id: "non-contrastive-ssl",
      title: "Non-contrastive SSL (BYOL, DINO)",
      goal: "Avoid negatives entirely with predictor networks (BYOL) and student-teacher distillation (DINO).",
      prerequisites: ["contrastive-ssl"],
      codeExempt: true,
    },
    {
      id: "mlm",
      title: "Masked language modeling",
      goal: "Pretrain BERT-style encoders by masking tokens and predicting them from bidirectional context.",
      prerequisites: ["D3/transformer-arch"],
      codeExempt: true,
    },
    {
      id: "mim",
      title: "Masked image modeling",
      goal: "Apply the masked-token objective to image patches (MAE, BEiT) to pretrain vision Transformers.",
      prerequisites: ["mlm", "D2/vit"],
      codeExempt: true,
    },
  ],
  D6: [
    {
      id: "graph-basics",
      title: "Graphs for learning",
      goal: "Represent a graph by its adjacency and feature matrices, and state the node, edge, and graph-level learning tasks.",
      prerequisites: ["A5/graph-traversal"],
    },
    {
      id: "message-passing",
      title: "Message passing",
      goal: "Define the message-passing framework as alternating message, aggregation, and update steps over node neighborhoods.",
      prerequisites: ["graph-basics"],
    },
    {
      id: "gcn-gat",
      title: "GCN, GraphSAGE, GAT",
      goal: "Instantiate message passing with normalized-Laplacian smoothing (GCN), sampled neighborhoods (GraphSAGE), and attention weights (GAT).",
      prerequisites: ["message-passing"],
    },
    {
      id: "graph-transformer",
      title: "Graph Transformers",
      goal: "Replace local message passing with global attention augmented by structural / positional encodings.",
      prerequisites: ["gcn-gat", "D3/transformer-arch"],
      codeExempt: true,
    },
    {
      id: "equivariant-dl",
      title: "Equivariant and geometric deep learning",
      goal: "Build networks whose outputs transform predictably under symmetry groups (E(3)-equivariant nets for molecules).",
      prerequisites: ["graph-basics"],
      codeExempt: true,
    },
  ],
  D7: [
    {
      id: "mixed-precision-dl",
      title: "Mixed-precision training",
      goal: "Train networks in fp16 or bf16 with master fp32 weights and loss scaling, picking the right format per layer.",
      prerequisites: ["A4/mixed-precision"],
    },
    {
      id: "gradient-checkpointing",
      title: "Gradient checkpointing",
      goal: "Trade compute for memory by recomputing activations during the backward pass instead of storing them.",
      prerequisites: ["D1/backprop"],
      codeExempt: true,
    },
    {
      id: "data-parallel",
      title: "Data parallelism (DDP, FSDP, ZeRO)",
      goal: "Split a global batch across devices, shard parameters and optimizer state (FSDP / ZeRO), and synchronize gradients.",
      prerequisites: ["mixed-precision-dl"],
      codeExempt: true,
    },
    {
      id: "model-parallel",
      title: "Pipeline and tensor parallelism",
      goal: "Split a single model across devices via pipeline stages (GPipe, 1F1B) and tensor parallelism (Megatron).",
      prerequisites: ["data-parallel"],
      codeExempt: true,
    },
    {
      id: "compilation",
      title: "Compilation (torch.compile, XLA, Triton)",
      goal: "Trace, fuse, and lower DL graphs through torch.compile, XLA, and custom Triton kernels for speed.",
      codeExempt: true,
    },
    {
      id: "flash-attention",
      title: "FlashAttention",
      goal: "Tile attention into SRAM-fitting blocks, recompute softmax statistics, and avoid materializing the n x n attention matrix.",
      prerequisites: ["D3/self-attention"],
      codeExempt: true,
    },
    {
      id: "training-infrastructure",
      title: "Training infrastructure overview",
      goal: "Survey the cluster pieces needed to train modern models: storage, schedulers, NCCL / collective comms, and observability.",
      codeExempt: true,
    },
  ],
};
