import { MDXRemote } from "next-mdx-remote/rsc";
import remarkMath from "remark-math";
import remarkGfm from "remark-gfm";
import rehypeKatex from "rehype-katex";
import rehypeUnwrapImages from "rehype-unwrap-images";
import type { MDXComponents } from "mdx/types";
import { MdxPre } from "./MdxPre";
import { FN, FNItem, Footnotes } from "./Footnotes";

/**
 * Renders a markdown image as a captioned `<figure>`. Lesson figures are static
 * SVGs generated by `figures/gen/<sub>.py` into `public/figures/`; the `alt`
 * text doubles as the visible caption. Styling (card surface, border) lives in
 * `.mdx-body img` / `figcaption` in globals.css.
 *
 * `rehype-unwrap-images` (below) strips the paragraph MDX puts around a
 * standalone image, so this block `<figure>` is not emitted inside a `<p>`
 * (invalid HTML → hydration mismatch).
 */
function MdxImage({ src, alt }: { src?: string; alt?: string }) {
  if (!src) return null;
  return (
    <figure>
      {/* Static pre-generated SVGs; next/image adds no value and breaks the MDX img mapping. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={src} alt={alt ?? ""} loading="lazy" />
      {alt ? <figcaption>{alt}</figcaption> : null}
    </figure>
  );
}

const components: MDXComponents = {
  pre: MdxPre as MDXComponents["pre"],
  img: MdxImage as MDXComponents["img"],
  // Paper-style citations (see Footnotes.tsx + content/STYLE.md §9).
  FN: FN as unknown as MDXComponents["a"],
  FNItem: FNItem as unknown as MDXComponents["li"],
  Footnotes: Footnotes as unknown as MDXComponents["section"],
};

/** Compiles and renders a subsection's MDX body (math via KaTeX, code via MdxPre). */
export function MdxContent({ source }: { source: string }) {
  return (
    <div className="mdx-body">
      <MDXRemote
        source={source}
        components={components}
        options={{
          mdxOptions: {
            // GFM enables pipe tables in lesson prose. `singleTilde: false`
            // keeps `~` from being parsed as strikethrough, which would clash
            // with math/text; remarkMath still owns `$...$` and `$$...$$`, so
            // pipes inside math (|x|, P(A|B), determinants) are untouched.
            remarkPlugins: [[remarkGfm, { singleTilde: false }], remarkMath],
            rehypePlugins: [rehypeKatex, rehypeUnwrapImages],
          },
        }}
      />
    </div>
  );
}
