import { MDXRemote } from "next-mdx-remote/rsc";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import type { MDXComponents } from "mdx/types";
import { MdxPre } from "./MdxPre";

/**
 * Renders a markdown image as a captioned `<figure>`. Lesson figures are static
 * SVGs generated by `figures/gen/<sub>.py` into `public/figures/`; the `alt`
 * text doubles as the visible caption. Styling (card surface, border) lives in
 * `.mdx-body img` / `figcaption` in globals.css.
 */
function MdxImage({ src, alt }: { src?: string; alt?: string }) {
  if (!src) return null;
  return (
    <figure>
      {/* Static pre-generated SVGs; next/image adds no value and breaks the MDX img mapping. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={src} alt={alt ?? ""} loading="lazy" />
      {alt ? <figcaption>{alt}</figcaption> : null}
    </figure>
  );
}

const components: MDXComponents = {
  pre: MdxPre as MDXComponents["pre"],
  img: MdxImage as MDXComponents["img"],
};

/** Compiles and renders a subsection's MDX body (math via KaTeX, code via MdxPre). */
export function MdxContent({ source }: { source: string }) {
  return (
    <div className="mdx-body">
      <MDXRemote
        source={source}
        components={components}
        options={{
          mdxOptions: {
            remarkPlugins: [remarkMath],
            rehypePlugins: [rehypeKatex],
          },
        }}
      />
    </div>
  );
}
